/*
A. Thor
time limit per test2 seconds
memory limit per test256 megabytes
inputstandard input
outputstandard output

Thor is getting used to the Earth. As a gift Loki gave him a smartphone. There are n applications on this phone. Thor is fascinated by this phone.
He has only one minor issue: he can't count the number of unread notifications generated by those applications
(maybe Loki put a curse on it so he can't).

q events are about to happen (in chronological order). They are of three types:

Application x generates a notification (this new notification is unread).

Thor reads all notifications generated so far by application x (he may re-read some notifications).

Thor reads the first t notifications generated by phone applications (notifications generated in first t events of the first type).
It's guaranteed that there were at least t events of the first type before this event.
Please note that he doesn't read first t unread notifications, he just reads the very first t notifications generated on his phone and he may
re-read some of them in this operation.

Please help Thor and tell him the number of unread notifications after each event. You may assume that initially there are no notifications in the
phone.

Input
The first line of input contains two integers n and q (1 ≤ n, q ≤ 300 000) — the number of applications and the number of events to happen.

The next q lines contain the events. The i-th of these lines starts with an integer typei — type of the i-th event.
If typei = 1 or typei = 2 then it is followed by an integer xi.
Otherwise it is followed by an integer ti (1 ≤ typei ≤ 3, 1 ≤ xi ≤ n, 1 ≤ ti ≤ q).

Output
Print the number of unread notifications after each event.

Examples
inputCopy
3 4
1 3
1 1
1 2
2 3
outputCopy
1
2
3
2
inputCopy
4 6
1 2
1 4
1 2
3 3
1 3
1 3
outputCopy
1
2
3
0
1
2
Note
In the first sample:

Application 3 generates a notification (there is 1 unread notification).
Application 1 generates a notification (there are 2 unread notifications).
Application 2 generates a notification (there are 3 unread notifications).
Thor reads the notification generated by application 3, there are 2 unread notifications left.
In the second sample test:

Application 2 generates a notification (there is 1 unread notification).
Application 4 generates a notification (there are 2 unread notifications).
Application 2 generates a notification (there are 3 unread notifications).
Thor reads first three notifications and since there are only three of them so far, there will be no unread notification left.
Application 3 generates a notification (there is 1 unread notification).
Application 3 generates a notification (there are 2 unread notifications).
*/
#include<iostream>
#include<map>
//#include<queue>
using namespace std;
int a[300001],b[3000001];

int main()
{
    ios_base::sync_with_stdio(false);
    int n,q,type,app,count=0,i=0;
    //map<int,int> mp;
    //queue <int> Q;
    cin>>n>>q;
    // while(n--)
    // {
    //     mp[n]=0;
    // }
    while (q--)
    {
        cin>>type>>app;
        if(type==1)
        {
            a[i]=app;
            i++;
            //mp[app]+=1;
            count++;
        }
        else if (type==2)
        {
           for(int j=0; j<i ; j++)
           {
               if(a[j]==app && !b[j])
               {
                   count--;
                   b[j]=1;
               }
           }
        }
        else if (type==3)
        {
            int t=app;
           for(int j=0; j<t; j++)
           {
               if(!b[j])
                {   
                    b[j]=1;
                    count--;
                }
           }
        }

        cout<<count<<endl;
    }

    return 0;
}

/*
#include <cstdio>
#include <vector>
#include <set>
using namespace std;
 
int main(){
 
    long n , q; 
    scanf("%ld %ld", &n, &q);
    set<long> st;
    vector<long> a;
    vector<std::vector<long> > b(n + 1);
    long last(0);
 
    for(long t = 0; t < q; t++){
        long w, x; 
        scanf("%ld %ld", &w, &x);
        if(w == 1)
        {
            a.push_back(t); 
            b[x].push_back(t); 
            st.insert(t);
        }
        else if(w == 2)
        {
            for(int u = 0; u < b[x].size(); ++ u)
                st.erase(b[x][u]);
            b[x].clear();
        }
        else if(w == 3)
        {
            while(last < x)
            {
                st.erase(a[last]); 
                last++;
            }
        }
        printf("%ld\n", st.size());
    }
 
    return 0;
}
}
*/